### ISSUE TITLE
ユーザ管理で「アプリケーションで問題が発生しました。」

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter.NetCore#1]
CentOS Linux release 7.5.1804 (Core)へインストールしたが、ユーザ管理を選択すると「アプリケーションで問題が発生しました。」を表示してユーザを追加できない。
なお、組織、グループは追加可能。
サーバ構成
・dotnet-host.x86_64
・dotnet-hostfxr-2.1.x86_64
・dotnet-runtime-2.1.x86_64
・dotnet-runtime-deps-2.1.x86_64
・dotnet-sdk-2.1.x86_64
・mssql-server.x86_64
・mssql-tools.x86_64

ログの確認方法を教示していただければ、確認します。

**Comment by koikoi0407** [comment]
追加情報です。ＤＢからエラー情報を記載します。
ErrMessage:

Object reference not set to an instance of an object.

ErrStackTrace:

   at Implem.Pleasanter.Libraries.Extensions.TdExtensions.<>c__DisplayClass1_0.<Td>b__0() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Extensions\TdExtensions.cs:line 23
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Libraries.Models.GridData.<>c__DisplayClass9_2.<TBody>b__3(Column column) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Models\GridData.cs:line 228
   at System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Libraries.Models.GridData.<>c__DisplayClass9_0.<TBody>b__0(DataRow dataRow) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Models\GridData.cs:line 178
   at System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Models.UserUtilities.<>c__DisplayClass4_0.<Grid>b__0() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 184
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Models.UserUtilities.Grid(HtmlBuilder hb, SiteSettings ss, GridData gridData, View view) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 176
   at Implem.Pleasanter.Models.UserUtilities.<>c__DisplayClass0_0.<Index>b__2() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 61
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Models.UserUtilities.<>c__DisplayClass0_0.<Index>b__1() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 56
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Models.UserUtilities.<>c__DisplayClass0_0.<Index>b__0() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 50
   at Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass2_0.<Content>b__0() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:line 125
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass1_0.<MainContainer>b__0() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:line 75
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 63
   at Implem.Pleasanter.Models.UserUtilities.Index(SiteSettings ss) in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Users\UserUtilities.cs:line 41
   at Implem.Pleasanter.Controllers.UsersController.Index() in C:\Users\koike\Desktop\Pleasanter\Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Controllers\UsersController.cs:line 22
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by jakenjarvis** [comment]
ubuntu18.04(ubuntu-ja-18.04-desktop-amd64.iso)でも、同様のエラーを確認しました。
ブラウザ画面最下部の赤い帯で、該当メッセージが表示されますね。

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。
Linuxでは動作時のデフォルト値がAsia/Tokyoとなるようになりました。
最新版では動作するようになっております。
是非ご確認ください。
