### ISSUE TITLE
デバイスのカメラの使用がhttp環境ではできなくなりました。

### ISSUE THREAD

**Issue by ken-ohno0714** [Implem/Implem.Pleasanter.NetCore#107]
前までは使用できたのですが、内容欄のカメラやビデオのボタンをおすとエラーが発生するようになりました。
エラー　→　Uncaught TypeError: Cannot read properties of undefined (reading 'getUserMedia')
内部で使用しているのでSSL化していなかったのですが、SSL化するしか解決策はないのでしょうか、、、

**Comment by ken-ohno0714** [comment]
Uncaught Error: Syntax error, unrecognized expression: [{"Method":"Log","Value":""},{"Method":"Message","Value":"{\"Id\":\"ApplicationError\",\"Text\":\"アプリケーションで問題が発生しました。\",\"Css\":\"alert-error\"}"}]
    at se.error (jquery-3.6.0.min.js:2:13639)
    at se.tokenize (jquery-3.6.0.min.js:2:21650)
    at se.select (jquery-3.6.0.min.js:2:22477)
    at Function.se [as find] (jquery-3.6.0.min.js:2:7116)
    at S.fn.init.find (jquery-3.6.0.min.js:2:25047)
    at new S.fn.init (jquery-3.6.0.min.js:2:25536)
    at S (jquery-3.6.0.min.js:2:1051)
    at Object.<anonymous> (generals.min.js?v=7d974946cafa8642c13392cb41c50e81a47a41fe3d565f102a5ca0e533524d86bd52b4f0583d5eacfcbf965b245c0846c176c9dd7e162e23186ae19aad6dbd11:1:2998)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as rejectWith] (jquery-3.6.0.min.js:2:29072)

**Comment by ken-ohno0714** [comment]
調べると、引用符に関するエラーの可能性があるらしいとの事で、、、
 
            return CanUploadImage(
                context: context,
                ss: ss,
                readOnly: readOnly,
                allowImage: allowImage,
                preview: preview)
                    ? hb
                        .Div(
                            attributes: new HtmlAttributes()
                                .Class("ui-icon ui-icon-image button-upload-image")
                                .OnClick($"$p.selectImage('{controlId}');"))
                        .Div(
                            attributes: new HtmlAttributes()
                                .Class("ui-icon ui-icon-video")
                                .OnClick($"$p.openVideo('{controlId}');"),
                            _using: !mobile)
                        .TextBox(
                            controlId: controlId + ".upload-image-file",
                            controlCss: "hidden upload-image-file",
                            textType: HtmlTypes.TextTypes.File,
                            accept: "image/*",
                            dataId: controlId)
                    : hb;

か

$p.selectImage = function (controlId) {
    $('[id="' + controlId + '.upload-image-file"]').click();
}

このあたりでしょうか、、、
