### ISSUE TITLE
SQLServerからPostgresqlへのマイグレーションで「アプリケーションで問題が発生しました。」

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter.NetCore#15]
該当アプリケーションを選択した時点でエラーとなる。
他のアプリケーションは問題なく開く。

バージョン：1.1.1.1

ErrMessage：42883: 演算子が存在しません: integer ~ unknown

ErrStackTrace
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Implem.Libraries.DataSources.SqlServer.SqlIo.<>c__DisplayClass17_0.<ExecuteDataSet>b__0() in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 217
   at Implem.Libraries.DataSources.SqlServer.SqlIo.Try(ISqlObjectFactory factory, Action action) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 295
   at Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteDataSet(ISqlObjectFactory factory, IDbTransaction dbTransaction, IDbConnection dbConnection) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 224
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteDataSet(Context context, IDbTransaction dbTransaction, IDbConnection dbConnection, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 316
   at Implem.Pleasanter.Libraries.DataSources.Repository.<>c__DisplayClass11_0.<ExecuteDataSet>b__0(IDbTransaction transaction, IDbConnection connection) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Repository.cs:line 342
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar[T](Context context, String connectionString, Boolean transactional, Func`3 func) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 255
   at Implem.Pleasanter.Libraries.Models.GridData.Get(Context context, SiteSettings ss, View view, TableTypes tableType, SqlColumnCollection column, SqlJoinCollection join, SqlWhereCollection where, Int32 top, Int32 offset, Int32 pageSize) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\Models\GridData.cs:line 101
   at Implem.Pleasanter.Libraries.Models.GridData..ctor(Context context, SiteSettings ss, View view, Nullable`1 tableType, SqlColumnCollection column, SqlJoinCollection join, SqlWhereCollection where, Int32 top, Int32 offset, Int32 pageSize) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\Models\GridData.cs:line 47
   at Implem.Pleasanter.Models.ResultUtilities.GetGridData(Context context, SiteSettings ss, View view, Int32 offset) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultUtilities.cs:line 188
   at Implem.Pleasanter.Models.ResultUtilities.Index(Context context, SiteSettings ss) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultUtilities.cs:line 33
   at Implem.Pleasanter.Models.ItemModel.Index(Context context) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Models\Items\ItemModel.cs:line 208
   at Implem.Pleasanter.Controllers.ItemsController.Index(Context context, Int64 id) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 14
   at Implem.Pleasanter.NetCore.Controllers.ItemsController.Index(Int64 id) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by koikoi0407** [comment]
#21と同様と考えられますのでクローズします。
