### ISSUE TITLE
「サイトのアクセス制御」で名前を入力、検索で「アプリケーションで問題が発生しました。」

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter.NetCore#17]
検索時のみエラーとなり、アクセス制御の設定は可能。
以下にSysLogsの情報を転機しますので、お手数ですが調査をお願いします。

バージョン：1.1.3.0
Method：searchpermissionelements
RequestData：VerUp=false&Sites_Timestamp=2020%2f7%2f8+8%3a14%3a44.930&SearchPermissionElements=%e9%88%b4%e6%9c%a8&ControlId=SearchPermissionElements&SourcePermissionsOffset=100
ErrMessage:42883： 演算子が存在しません: integer ~~ text
ErrStackTrace：
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at Implem.PostgreSql.PostgreSqlDataAdapter.Fill(DataTable dataTable) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Rds\Implem.PostgreSql\PostgreSqlDataAdapter.cs:line 105
   at Implem.Libraries.DataSources.SqlServer.SqlIo.Try(ISqlObjectFactory factory, Action action) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 295
   at Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteTable(ISqlObjectFactory factory, IDbTransaction dbTransaction, IDbConnection dbConnection) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 193
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteTable(Context context, IDbTransaction dbTransaction, IDbConnection dbConnection, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 292
   at Implem.Pleasanter.Libraries.DataSources.Repository.<>c__DisplayClass10_0.<ExecuteTable>b__0(IDbTransaction transaction, IDbConnection connection) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Repository.cs:line 322
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar[T](Context context, String connectionString, Boolean transactional, Func`3 func) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 255
   at Implem.Pleasanter.Models.PermissionUtilities.SourceCollection(Context context, SiteSettings ss, String searchText, List`1 currentPermissions, Int32 offset) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 371
   at Implem.Pleasanter.Models.PermissionUtilities.SearchPermissionElements(Context context, Int64 referenceId) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 844
   at Implem.Pleasanter.Controllers.ItemsController.SearchPermissionElements(Context context, Int64 id) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 759
   at Implem.Pleasanter.NetCore.Controllers.ItemsController.SearchPermissionElements(Int64 id) in D:\git\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 854
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by koikoi0407** [comment]
実行時のPostgresql LOGを追記します。

[2020-07-09 08:28:12 JST]bcpdb_User bcpdb 2108[1350]LOG:  期間: 0.022 ミリ秒  実行 <unnamed>: select "Groups"."TenantId","Groups"."GroupId","Groups"."Ver","Groups"."GroupName","Groups"."Body","Groups"."Comments","Groups"."Creator","Groups"."Updator","Groups"."CreatedTime","Groups"."UpdatedTime" from "Groups" as "Groups" where ("Groups"."TenantId"=$1) and ("Groups"."GroupId"=$2)
[2020-07-09 08:28:12 JST]bcpdb_User bcpdb 2108[1351]詳細:  パラメータ: $1 = '1', $2 = '36'
[2020-07-09 08:28:12 JST]bcpdb_User bcpdb 2108[1352]LOG:  期間: 0.042 ミリ秒  文: DISCARD ALL
[2020-07-09 08:28:12 JST]bcpdb_User bcpdb 2108[1353]ERROR:  演算子が存在しません: integer ~~ text(463文字目)
[2020-07-09 08:28:12 JST]bcpdb_User bcpdb 2108[1354]ヒント:  指定した名称と引数の型に合う演算子がありません。明示的な型キャストが必要かもしれません。

**Comment by koikoi0407** [comment]
バージョン：1.1.3.2で「アプリケーションで問題が発生しました。」は解消されました。
しかし、検索時にユーザ名での検索ができません。
※組織名、グループ名での検索は可能。
　.NET Framework版ではユーザ名で検索可能です。

**Comment by koikoi0407** [comment]
ユーザデータが移行されていないので検索ができませんでした。
手動でユーザデータを移行して検索できることを確認しました。
本件、クローズします。
