### ISSUE TITLE
NullReferenceException が発生し、CodeDefinerが実行できない。

### ISSUE THREAD

**Issue by ShortArrow** [Implem/Implem.Pleasanter.NetCore#25]
#内容
[Pleasanter with PostgreSQLをRHEL8/CentOS8にインストールする](https://pleasanter.net/fs/publishes/1490231/edit)に従って、
CENTOS8にインストールした時、`dotnet Implem.CodeDefiner.NetCore.dll _rds`の部分で以下のエラーが出て先に進めません。

```bash:
[root@localhost Implem.CodeDefiner]# dotnet Implem.CodeDefiner.NetCore.dll _rds
<ERROR> <>c.<Main>b__1_0: UnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Implem.DefinitionAccessor.Initializer.SetRdsParameters() in D:\git\Implem.Pleasanter.NetCore.Private\Implem.DefinitionAccessor\Initializer.cs:line 421
   at Implem.DefinitionAccessor.Initializer.Initialize(String path, String assemblyVersion, Boolean codeDefiner, Boolean setSaPassword, Boolean setRandomPassword) in D:\git\Implem.Pleasanter.NetCore.Private\Implem.DefinitionAccessor\Initializer.cs:line 30
   at Implem.CodeDefiner.Starter.Main(String[] args) in D:\git\Implem.Pleasanter.NetCore.Private\Implem.CodeDefiner\Starter.cs:line 41
   at Implem.CodeDefiner.NetCore.Program.Main(String[] args) in D:\git\Implem.Pleasanter.NetCore.Private\Implem.CodeDefiner.NetCore\Program.cs:line 10
```
#環境
Linux localhost.localdomain 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
psql (PostgreSQL) 12.1
Microsoft.AspNetCore.App 3.1.7 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.7 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

**Comment by ShortArrow** [comment]
「最小限のインストール」を選択していると、手順通りでは上手くいきません。
しかし、通常の「サーバー」を選択していれば問題なく動作しました。
![image](https://user-images.githubusercontent.com/16986253/93424956-14080500-f8f4-11ea-9b5b-5ba768bc68f8.png)
バグではなく仕様と分かったためIssueを閉じます。
