### ISSUE TITLE
レコードのアクセス制御でエラーが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter.NetCore#43]
編集画面からレコードのアクセス制御タブを選択すると下記の様なエラーが発生し、開くことが出来ません。
Ver.は1.2.7.0です。

```
Value cannot be null. (Parameter 'input')
```

```
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Matches(String input)
   at Implem.Pleasanter.Libraries.DataTypes.User.SelectableText(Context context, String format) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataTypes\User.cs:line 182
   at Implem.Pleasanter.Libraries.Security.Permission.ControlData(Context context, SiteSettings ss, Boolean withType) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Security\Permission.cs:line 123
   at Implem.Pleasanter.Models.PermissionUtilities.<>c__DisplayClass2_0.<ListItemCollection>b__1(Permission o) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 116
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Implem.Pleasanter.Models.PermissionUtilities.ListItemCollection(List`1 permissions, Context context, SiteSettings ss, Boolean withType) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 114
   at Implem.Pleasanter.Models.PermissionUtilities.PermissionEditor(HtmlBuilder hb, Context context, SiteSettings ss, Int64 referenceId, Boolean _using) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 227
   at Implem.Pleasanter.Models.PermissionUtilities.<>c__DisplayClass3_0.<Permission>b__1() in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 138
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 101
   at Implem.Pleasanter.Models.PermissionUtilities.<>c__DisplayClass3_0.<Permission>b__0() in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 133
   at Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:line 101
   at Implem.Pleasanter.Models.PermissionUtilities.Permission(HtmlBuilder hb, Context context, SiteModel siteModel, Int64 referenceId, Boolean site) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 129
   at Implem.Pleasanter.Models.PermissionUtilities.Permission(Context context, Int64 referenceId) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Permissions\PermissionUtilities.cs:line 81
   at Implem.Pleasanter.Controllers.ItemsController.Permissions(Context context, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 751
   at Implem.Pleasanter.NetCore.Controllers.ItemsController.Permissions(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 843
   at lambda_method2453(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by uchi-ta** [comment]
Permissions.jsonに新しいパラメータが追加されていますので、そちらが古いバージョンのパラメータファイルで削除されている可能性があります。

https://github.com/Implem/Implem.Pleasanter.NetCore/blob/master/Implem.Pleasanter/App_Data/Parameters/Permissions.json

下記の項目を追加して再起動後にリトライしてみてください。

    "DeptFormat": "[[Dept] [DeptId]] [DeptName]",
    "GroupFormat": "[[Group] [GroupId]] [GroupName]",
    "UserFormat": "[[User] [UserId]] [Name]"

**Comment by kazuca** [comment]
ありがとうございます。パラメータが抜けていたので追加したところ解決しました。
