### ISSUE TITLE
Ver.1.2.7.0がUbuntuで起動しない。

### ISSUE THREAD

**Issue by funakura** [Implem/Implem.Pleasanter.NetCore#44]
Ver:1.2.7.0
OS:ubuntu 20.04
DB:PostgreSQL
使用バイナリ：https://pleasanter.org/downloads/Pleasante_1.2.7.0.zip

Ver1.2.6.0稼働環境・新規構築環境で、プリザンタが例外で起動しません。
※ソースコードをVSで稼働すると正常に動作します。(Windows環境)

１：Implem.CodeDefiner によるテーブル構築で失敗する。
 $dotnet Implem.CodeDefiner.NetCore.dll _rds
エラーメッセージは以下

<ERROR> <>c.<Main>b__1_0: UnhandledException: System.IO.IOException: Directory not empty
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Implem.Libraries.Utilities.Files.<>c__DisplayClass16_0.<DeleteTemporaryFiles>b__1(String dirPath) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Files.cs:line 263
   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 13
   at Implem.Libraries.Utilities.Files.DeleteTemporaryFiles(String path, Int32 timeElapsed) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Files.cs:line 258
   at Implem.DefinitionAccessor.Initializer.DeleteTemporaryFiles() in C:\Implem\Pleasanter.NetCore\Implem.DefinitionAccessor\Initializer.cs:line 707
   at Implem.DefinitionAccessor.Initializer.Initialize(String path, String assemblyVersion, Boolean codeDefiner, Boolean setSaPassword, Boolean setRandomPassword) in C:\Implem\Pleasanter.NetCore\Implem.DefinitionAccessor\Initializer.cs:line 43
   at Implem.CodeDefiner.Starter.Main(String[] args) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Starter.cs:line 41
   at Implem.CodeDefiner.NetCore.Program.Main(String[] args) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner.NetCore\Program.cs:line 10

２：Pleasanterの起動で失敗する。
 $dotnet Implem.Pleasanter.NetCore.dll
エラーメッセージは以下

Unhandled exception. System.IO.IOException: Directory not empty
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Implem.Libraries.Utilities.Files.<>c__DisplayClass16_0.<DeleteTemporaryFiles>b__1(String dirPath) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Files.cs:line 263
   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 13
   at Implem.Libraries.Utilities.Files.DeleteTemporaryFiles(String path, Int32 timeElapsed) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Files.cs:line 258
   at Implem.DefinitionAccessor.Initializer.DeleteTemporaryFiles() in C:\Implem\Pleasanter.NetCore\Implem.DefinitionAccessor\Initializer.cs:line 707
   at Implem.DefinitionAccessor.Initializer.Initialize(String path, String assemblyVersion, Boolean codeDefiner, Boolean setSaPassword, Boolean setRandomPassword) in C:\Implem\Pleasanter.NetCore\Implem.DefinitionAccessor\Initializer.cs:line 43
   at Implem.Pleasanter.NetCore.Startup..ctor(IConfiguration configuration, IWebHostEnvironment env) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Startup.cs:line 48
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Implem.Pleasanter.NetCore.Program.Main(String[] args) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Program.cs:line 10
Aborted

以上

**Comment by funakura** [comment]
以下バイナリで改善しました。
https://pleasanter.org/downloads/Pleasante_1.2.8.0.zip
