### ISSUE TITLE
画像の登録ができない

### ISSUE THREAD

**Issue by march5176** [Implem/Implem.Pleasanter.NetCore#91]
【動作環境】
- サーバー
 Pleasanter 1.3.13.0
 Rocky Linux 8.6
 dotnet-runtime 6.0.6
 dotnet-sdk 6.0.106
 libdgiplus 6.0.5
PostgreSQL 14.4

- クライアント
 Windows10 + Microsoft Edge 103.0.1264.44  

【症状】
Wikiやマークダウンに画像を登録できない

【サーバーログ】
```
PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.,   at System.Drawing.Image.FromStream(Stre
am stream)
   at Implem.Pleasanter.Libraries.Images.ImageData..ctor(Byte[] data, Int64 referenceId, Types type) in C:\Implem\Pleasanter.NetCor
e\Implem.Pleasanter\Libraries\Images\ImageData.cs:line 31
   at Implem.Pleasanter.Models.BinaryUtilities.UploadImage(Context context, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Binaries\BinaryUtilities.cs:line 435
   at Implem.Pleasanter.Controllers.BinariesController.UploadImage(String reference, Int64 id, ICollection`1 file) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\BinariesController.cs:line 130
   at lambda_method776(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted),,1.3.13.0,,4,4,2022-07-06 15:16:05.909
```

**Comment by march5176** [comment]
dotnet のバイナリを公式サイトのtarballに切り替えると改善。(OSのパッケージからインストールした dotnet で問題が発生している）
